# Use the base image you need (e.g., node:14)
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the required files from Modules folder
COPY ../Modules /app/Modules

# Copy the application files
COPY . .

# Build commands (if applicable)
RUN npm install
RUN npm run build

# Define the command to start the application
CMD ["npm", "start"]
